import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex flex row justify-center">
            <li>
              <Link className="p-10" href="/">Home</Link>
            </li>
            <li>
              <Link className="p-10" href="/showcase">Showcase</Link>
            </li>
            <li>
              <Link className="p-10" href="/about">About</Link>
            </li>
          </ul>
        </nav>
        {children}</body>
    </html>
  )
}
